CREATE TABLE IF NOT EXISTS apps
(
    id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS endpoint_hits
(
    id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app_id    BIGINT REFERENCES apps (id) ON DELETE CASCADE,
    uri       VARCHAR(512) NOT NULL,
    ip        VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE
);

DELETE from apps;
DELETE from endpoint_hits;

ALTER TABLE apps ALTER COLUMN id RESTART WITH 1;
ALTER TABLE endpoint_hits ALTER COLUMN id RESTART WITH 1;